import type { Metadata } from "next";
import { Inter, Calistoga, Lato } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { twMerge } from "tailwind-merge";
import { BaseModal } from "@/elements/BaseModal";
//const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const lato = Lato({
  subsets: ["latin"],
  // css variable for tailwind-config
  variable: "--font-lato",
  weight: "400",
});

// static metadata
export const metadata: Metadata = {
  title: "next js template app 1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{
        height: "100%",
      }}
    >
      <body
        //suppressHydrationWarning={true}
        className={twMerge(
          "#bg-gray-900 #text-white antialiased font-lato overflow-x-hidden",
          lato.variable
        )}
        style={{
          height: "100%",
        }}
      >
        <Providers>
          {children}
          <BaseModal />
        </Providers>
      </body>
    </html>
  );
}
